site_name: Loopy Agents - Claude Code Mastery
site_description: Master Claude Code with hooks, agents, MCP servers, and automation patterns
site_author: LoopTech AI
site_url: https://looptech-ai.github.io/loopy-agents-doc/
repo_url: https://github.com/looptech-ai/loopy-agents-doc
repo_name: looptech-ai/loopy-agents-doc
edit_uri: edit/main/docs/

theme:
  name: material
  custom_dir: overrides
  logo: assets/logo.svg
  favicon: assets/favicon.png
  
  palette:
    # Dark mode as default
    - scheme: slate
      primary: deep purple
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    
    # Light mode
    - scheme: default
      primary: deep purple
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  
  font:
    text: Inter
    code: JetBrains Mono
  
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - toc.follow
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - announce.dismiss
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - content.action.edit
    - content.action.view

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
      lang:
        - en
  - minify:
      minify_html: true
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - tags:
      tags_file: tags.md

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
      auto_title: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra:
  analytics:
    provider: google
    property: G-XXXXXXXXXX
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/looptech-ai
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/@looptech-ai
    - icon: fontawesome/brands/discord
      link: https://discord.gg/looptech-ai
  generator: false
  version:
    provider: mike

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js

nav:
  - Home:
    - index.md
    - getting-started.md
    - architecture.md
  
  - Hooks:
    - hooks/index.md
    - hooks/lifecycle.md
    - hooks/security.md
    - hooks/examples.md
    - hooks/debugging.md
  
  - Agents:
    - agents/index.md
    - agents/single-file.md
    - agents/multi-agent.md
    - agents/voice-enabled.md
    - agents/patterns.md
  
  - MCP Servers:
    - mcp/index.md
    - mcp/nano-agent.md
    - mcp/just-prompt.md
    - mcp/custom-servers.md
    - mcp/integration.md
  
  - Memory:
    - memory/index.md
    - memory/hierarchy.md
    - memory/claude-md.md
    - memory/best-practices.md
  
  - Observability:
    - observability/index.md
    - observability/monitoring.md
    - observability/real-time.md
    - observability/debugging.md
  
  - Extensions:
    - extensions/index.md
    - extensions/claudia.md
    - extensions/alternatives.md
    - extensions/custom.md
  
  - Patterns:
    - patterns/index.md
    - patterns/automation.md
    - patterns/security.md
    - patterns/performance.md
    - patterns/team-collaboration.md
  
  - Examples:
    - examples/index.md
    - examples/quick-start.md
    - examples/advanced.md
    - examples/real-world.md
  
  - Reference:
    - reference/index.md
    - reference/commands.md
    - reference/api.md
    - reference/troubleshooting.md
    - reference/glossary.md
    - tags.md

copyright: |
  &copy; 2025 <a href="https://github.com/looptech-ai" target="_blank" rel="noopener">LoopTech AI</a>