site_name: Loopy Agents - Claude Code Mastery
site_description: Master Claude Code with hooks, agents, MCP servers, and automation patterns
site_author: LoopTech AI
site_url: https://looptech-ai.github.io/loopy-agents-doc/
repo_url: https://github.com/looptech-ai/loopy-agents-doc
repo_name: looptech-ai/loopy-agents-doc
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    # Dark mode as default
    - scheme: slate
      primary: deep purple
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    
    # Light mode
    - scheme: default
      primary: deep purple
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  
  font:
    text: Inter
    code: JetBrains Mono
  
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
    - content.tabs.link

plugins:
  - search:
      lang:
        - en

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
      auto_title: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/looptech-ai
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/@looptech-ai
    - icon: fontawesome/brands/discord
      link: https://discord.gg/loopy-agents
  generator: false

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  
  - Hooks:
    - Overview: hooks/index.md
    - Lifecycle: hooks/lifecycle.md
  
  - Agents:
    - Overview: agents/index.md
  
  - MCP Servers:
    - Overview: mcp/index.md

copyright: |
  &copy; 2025 <a href="https://github.com/looptech-ai" target="_blank" rel="noopener">LoopTech AI</a>